import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

async function updateReadmeMetrics() {
  console.log('Reading Autonomous QA metrics from artifact...');
  const metricsFilePath = path.join(process.cwd(), 'qa-metrics.json');
  const metricsContent = readFileSync(metricsFilePath, 'utf-8');
  const metrics = JSON.parse(metricsContent);
  console.log('Metrics collected:', metrics);
  
  const readmeContent = readFileSync('README.md', 'utf-8');

  const lastRun = metrics.lastRun
    ? new Date(metrics.lastRun).toUTCString()
    : new Date().toUTCString();

  // Everything between the markers is auto-generated. Content outside is never touched.
  const autoGenContent = `\n<!-- auto-generated by CI — do not edit between these markers -->\n**Autonomous QA Metrics (Last Run: ${lastRun}):**\n| Metric | Value |\n|---|---|\n| Queries Executed | ${metrics.totalQueriesExecuted} |\n| Anomalies Detected | ${metrics.totalAnomaliesDetected} |\n| High Severity | ${metrics.highSeverityAnomalies} |\n| Medium Severity (Latency) | ${metrics.mediumSeverityAnomalies} |\n`;

  const startMarker = '<!-- AUTONOMOUS_QA_METRICS_START -->';
  const endMarker = '<!-- AUTONOMOUS_QA_METRICS_END -->';

  const startIndex = readmeContent.indexOf(startMarker);
  const endIndex = readmeContent.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1) {
    console.warn('Markers for Autonomous QA metrics not found in README.md. Skipping update.');
    return;
  }

  if (endIndex <= startIndex) {
    console.warn('End marker appears before start marker in README.md. Skipping update.');
    return;
  }

  const before = readmeContent.substring(0, startIndex + startMarker.length);
  const after = readmeContent.substring(endIndex);
  writeFileSync('README.md', before + autoGenContent + after, 'utf-8');
  console.log('README.md updated with new metrics.');
}

updateReadmeMetrics().catch(console.error);