/**
 * Regenerates tests/contract/query.compliance.test.ts from the current schema.graphql.
 *
 * Run via:  npm run schema:heal
 *
 * When to use:
 *   - A non-breaking schema change (new field added) — heal adds coverage for the new field.
 *   - A breaking schema change (field renamed/removed) — heal replaces the broken query
 *     with one derived from the current schema, then CI can pass again.
 *
 * After running, review the generated file:
 *   - Check that no previously-asserted field values were silently dropped.
 *   - Re-add value assertions for priority resolvers (e.g., mission_name === 'FalconSat').
 *   - Commit the regenerated file with a note in the commit message.
 */

import { buildSubgraphSchema } from '@apollo/subgraph';
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import gql from 'graphql-tag';
import resolvers from '../src/resolvers';
import { generateQueries } from '../src/qa/generators/query-generator';

const schemaSDL = readFileSync(resolve('schema.graphql'), 'utf-8');
const schema = buildSubgraphSchema({ typeDefs: gql(schemaSDL), resolvers });
const { queries, skippedFields } = generateQueries(schema, new Set(Object.keys(resolvers.Query ?? {})));

const groupHeaders: Record<string, string> = {
  launches: 'list resolvers',
  launchesPast: 'list resolvers',
  launchesUpcoming: 'list resolvers',
  capsules: 'list resolvers',
  capsulesPast: 'list resolvers',
  capsulesUpcoming: 'list resolvers',
  cores: 'list resolvers',
  coresPast: 'list resolvers',
  coresUpcoming: 'list resolvers',
  dragons: 'list resolvers',
  histories: 'list resolvers',
  landpads: 'list resolvers',
  launchpads: 'list resolvers',
  payloads: 'list resolvers',
  rockets: 'list resolvers',
  ships: 'list resolvers',
  launch: 'single-item resolvers',
  launchLatest: 'single-item resolvers',
  launchNext: 'single-item resolvers',
  capsule: 'single-item resolvers',
  core: 'single-item resolvers',
  dragon: 'single-item resolvers',
  history: 'single-item resolvers',
  landpad: 'single-item resolvers',
  launchpad: 'single-item resolvers',
  payload: 'single-item resolvers',
  rocket: 'single-item resolvers',
  ship: 'single-item resolvers',
  company: 'singleton resolvers',
  roadster: 'singleton resolvers',
  launchesPastResult: 'result-envelope resolvers',
  historiesResult: 'result-envelope resolvers',
  rocketsResult: 'result-envelope resolvers',
  shipsResult: 'result-envelope resolvers',
  missions: 'deprecated resolvers',
  mission: 'deprecated resolvers',
  missionsResult: 'deprecated resolvers',
};

// Group queries by section
const groups = new Map<string, Array<{ name: string; query: string }>>();
for (const query of queries) {
  const match = query.match(/\{\s*(\w+)/);
  const fieldName = match?.[1] ?? 'unknown';
  const group = groupHeaders[fieldName] ?? 'other';
  const existing = groups.get(group) ?? [];
  groups.set(group, [...existing, { name: fieldName, query }]);
}

function escapeBacktick(s: string): string {
  return s.replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

const sections: string[] = [];
for (const [group, entries] of groups) {
  const tests = entries.map(({ name, query }) =>
    `  it('${name}', () => assertValid('${name}', \`${escapeBacktick(query)}\`));`
  ).join('\n');
  sections.push(`describe('Contract: ${group}', () => {\n${tests}\n});`);
}

const output = `// AUTO-GENERATED by scripts/heal-compliance.ts — run \`npm run schema:heal\` to regenerate.
// After regeneration: review for missing field-value assertions on priority resolvers.
import { validate, parse, Source } from 'graphql';
import { readFileSync } from 'fs';
import path from 'path';
import { buildSubgraphSchema } from '@apollo/subgraph';
import gql from 'graphql-tag';

const SCHEMA_PATH = path.resolve(__dirname, '../../schema.graphql');
const schema = buildSubgraphSchema({
  typeDefs: gql(readFileSync(SCHEMA_PATH, 'utf-8')),
  resolvers: {},
});

function assertValid(name: string, query: string): void {
  const errors = validate(schema, parse(new Source(query, name)));
  if (errors.length > 0) {
    const details = errors.map(e => \`  [COMPLIANCE ERROR] \${e.message}\`).join('\\n');
    throw new Error(\`Production query breakage detected for "\${name}":\\n\${details}\`);
  }
  expect(errors).toHaveLength(0);
}

${sections.join('\n\n')}
${skippedFields.length > 0 ? `\n// Skipped (no selectable scalar subfields): ${skippedFields.join(', ')}\n` : ''}`;

const outPath = resolve('tests/contract/query.compliance.test.ts');
writeFileSync(outPath, output, 'utf-8');
console.log(`Wrote ${queries.length} compliance tests to ${outPath}`);
if (skippedFields.length > 0) {
  console.log(`Skipped fields (no scalar subfields reachable): ${skippedFields.join(', ')}`);
}
