/**
 * Patches three auto-generated sentinel blocks in README.md:
 *
 *   <!-- README_STATS_START --> … <!-- README_STATS_END -->
 *     → total test count + suite count (from .jest-results.json)
 *
 *   <!-- README_COVERAGE_START --> … <!-- README_COVERAGE_END -->
 *     → coverage table rows (from coverage/coverage-summary.json)
 *
 *   <!-- AUTONOMOUS_QA_METRICS_START --> … <!-- AUTONOMOUS_QA_METRICS_END -->
 *     → autonomous QA run metrics (from qa-metrics.json)
 *
 * Run via:  npm run readme:update
 * The npm script generates .jest-results.json and coverage/coverage-summary.json
 * before calling this file with ts-node.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

// ─── Helper ───────────────────────────────────────────────────────────────────

function replaceBetween(
  content: string,
  startTag: string,
  endTag: string,
  inner: string,
): string {
  const si = content.indexOf(startTag);
  const ei = content.indexOf(endTag);
  if (si === -1 || ei === -1 || ei <= si) {
    console.warn(`  [warn] sentinel not found or misordered: ${startTag}`);
    return content;
  }
  return content.slice(0, si + startTag.length) + '\n' + inner + '\n' + content.slice(ei);
}

// ─── Read inputs ──────────────────────────────────────────────────────────────

// 1. Jest JSON output — total test + suite count across all suites
let totalSuites = 0;
let totalTests = 0;
const JEST_RESULTS = resolve('.jest-results.json');
if (existsSync(JEST_RESULTS)) {
  const r = JSON.parse(readFileSync(JEST_RESULTS, 'utf-8'));
  totalSuites = r.numTotalTestSuites ?? 0;
  totalTests  = r.numTotalTests      ?? 0;
} else {
  console.warn('  [warn] .jest-results.json not found — test count will not be updated');
}

// 2. Coverage summary — SpaceX CI tests only
let stmts = '—', branches = '—', funcs = '—', lines = '—';
const COVERAGE_SUMMARY = resolve('coverage/coverage-summary.json');
if (existsSync(COVERAGE_SUMMARY)) {
  const { total } = JSON.parse(readFileSync(COVERAGE_SUMMARY, 'utf-8'));
  stmts    = total.statements.pct.toFixed(2) + '%';
  branches = total.branches.pct.toFixed(2)   + '%';
  funcs    = total.functions.pct.toFixed(2)  + '%';
  lines    = total.lines.pct.toFixed(2)      + '%';
} else {
  console.warn('  [warn] coverage/coverage-summary.json not found — coverage will not be updated');
}

// 3. QA metrics — written by autonomous runner when writeMetrics:true
let qaBlock = '';
const QA_METRICS = resolve('qa-metrics.json');
if (existsSync(QA_METRICS)) {
  const m    = JSON.parse(readFileSync(QA_METRICS, 'utf-8'));
  const date = new Date(m.lastRun).toUTCString();
  qaBlock = [
    `<!-- auto-generated by update-readme.ts — do not edit between markers -->`,
    `**Last Recorded Autonomous QA Metrics (${date}):**`,
    `| Metric | Value |`,
    `|---|---|`,
    `| Queries Executed | ${m.totalQueriesExecuted} |`,
    `| Anomalies Detected | ${m.totalAnomaliesDetected} |`,
    `| High Severity | ${m.highSeverityAnomalies} |`,
    `| Medium Severity (Latency) | ${m.mediumSeverityAnomalies} |`,
  ].join('\n');
} else {
  console.warn('  [warn] qa-metrics.json not found — QA metrics will not be updated');
}

// ─── Patch README ─────────────────────────────────────────────────────────────

let readme = readFileSync(resolve('README.md'), 'utf-8');

if (totalTests > 0) {
  readme = replaceBetween(
    readme,
    '<!-- README_STATS_START -->',
    '<!-- README_STATS_END -->',
    `This project uses a layered, seven-stage CI pipeline for GraphQL schema stability, ` +
    `runtime safety, and regression detection. All **${totalTests} tests** pass across ` +
    `**${totalSuites} suites**; HTTP is fully mocked by MSW so no live network calls occur in CI.`,
  );
}

if (stmts !== '—') {
  readme = replaceBetween(
    readme,
    '<!-- README_COVERAGE_START -->',
    '<!-- README_COVERAGE_END -->',
    [
      `| Statements | 55% | ${stmts} |`,
      `| Branches   | 60% | ${branches} |`,
      `| Functions  | 44% | ${funcs} |`,
      `| Lines      | 55% | ${lines} |`,
    ].join('\n'),
  );
}

if (qaBlock) {
  readme = replaceBetween(
    readme,
    '<!-- AUTONOMOUS_QA_METRICS_START -->',
    '<!-- AUTONOMOUS_QA_METRICS_END -->',
    qaBlock,
  );
}

writeFileSync(resolve('README.md'), readme, 'utf-8');

// ─── Summary ──────────────────────────────────────────────────────────────────

console.log('README.md updated:');
if (totalTests > 0)  console.log(`  tests    : ${totalTests} across ${totalSuites} suites`);
if (stmts !== '—')   console.log(`  coverage : stmts=${stmts}  branches=${branches}  funcs=${funcs}  lines=${lines}`);
if (qaBlock)         console.log(`  qa       : metrics block refreshed`);
